[project]
name = "transformers-aiayn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightning>=2.5.2",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "torch>=2.7.1",
    "torchtext>=0.18.0",
]
