MODEL_NUMBER_OF_LAYERS = 6
MODEL_DIMENSION = 512
MODEL_NUMBER_OF_HEADS = 8
MODEL_INNER_LAYER_DIMENSION = 2048
MODEL_DROPOUT_PROBABILITY = 0.1
MODEL_LABEL_SMOOTHING_VALUE = 0.1

BETA1 = 0.9
BETA2 = 0.98
EPSILON = 1e-9
WARMUP_STEPS = 4000

SOURCE_LANGUAGE = "en"
TARGET_LANGUAGE = "fr"

BOS_TOKEN = '<s>'
EOS_TOKEN = '</s>'
PAD_TOKEN = "<pad>"