NUMBER_OF_LAYERS = 6
NUMBER_OF_HEADS = 8
MODEL_DIMENSION = 512
KEY_DIMENSION = MODEL_DIMENSION / NUMBER_OF_HEADS
VALUE_DIMENSION = KEY_DIMENSION
INNER_LAYER_DIMENSION = 2048

DROPOUT_PROBABILITY = 0.1
LABEL_SMOOTHING = 0.1

BETA1 = 0.9
BETA2 = 0.98
EPSILON = 1e-9
WARMUP_STEPS = 4000